### ISSUE TITLE
Cable disappearing when chunks unload

### ISSUE THREAD

**Issue by wootaboot** [mrh0/createaddition#216] opened 2022-03-07 00:13 UTC
Describe the bug
Cables disappear when chunk is unloaded either by TP or when disconnecting from server

To Reproduce
Set up a machine or battery with wire connectors and a spool.
Teleport away, teleport back, cable gone/ disconnect from server and reconnect

Additional context

Minecraft version: 1.18.1
Mod version: createaddition-1.18.1-20220125a
Forge version: 39.0.79
Create version: create-mc1.18.1_v0.4d

**Comment by ascpial** [comment] 2022-03-13 20:52
I can add that the cables seem to disappear when the two nodes are located in the same chunk.

**Comment by mrh0** [comment] 2022-03-14 08:58
dup of #212

**Comment by mrh0** [comment] 2022-03-14 09:08
> 

Did exactly this, still unable to reproduce, I've had several of these bug reports but whatever I try I've never had this happen myself.

**Comment by UMAGODi** [comment] 2022-03-24 13:18
I have same issue but it occures ONLY in a forge multiplayer.
And another issue, torches have no light. (light-level around torches won't change when the chunk loaded)

I noticed that these problems occur in some specified chunk but I can't be sure. 

Server OS: CentOS Linux release 8.4.2105
Server Version: forge-1.18.1-39.1.0
Mod Version: createaddition-1.18.1-20220125a
Create Version: create-mc1.18.1_v0.4d

[2022-03-24-6.log](https://github.com/mrh0/createaddition/files/8341727/2022-03-24-6.log)

**Comment by mrh0** [comment] 2022-03-28 21:32
I think I fixed it in 20220328a, though haven't been able to verify it.

**Comment by UMAGODi** [comment] 2022-03-29 10:41
I confirmed that the issue has been fixed in my environment and hope the thread owner also will do it.

Thank you for your working.

**Closed** 2022-04-15 18:52 UTC
Labels: bug
