### ISSUE TITLE
Current version of Create Addition crashes with create-fabric-0.5.0.i-921+1.18.2.jar

### ISSUE THREAD

**Issue by Fade-Alchemist** [mrh0/createaddition#482] opened 2023-02-08 03:41 UTC
The current version of Create Addition crashes with create-fabric-0.5.0.i-921+1.18.2.jar

Steps to recreate - add both these mods in, create additions prevents game launch.

**Comment by MSandro** [comment] 2023-02-08 05:57
I hope this will be fixed very soon.

**Comment by JoelZBub** [comment] 2023-02-09 03:11
Duplicate of #474, #475 and #477

**Comment by FluffyBumblebees** [comment] 2023-02-10 14:48
I think the latest release has resolved this issue. Care to test it on your system to see if it works on your system as well?

**Comment by mrh0** [comment] 2023-02-11 16:34
Fixed in 20230211a.

**Closed by mrh0** 2023-02-11 16:34 UTC
Labels: bug, fabric
