### ISSUE TITLE
infinite energy - Wrong conversion rate of Alternator and or Motor 

### ISSUE THREAD

**Issue by MaggiMagieBruch** [mrh0/createaddition#696] opened 2023-12-05 13:03 UTC
**Describe the bug**
Infinite energy bug when just using 2 Alternators and 1 Electric motor
**To Reproduce**
Place 1 Electricmotor and 2 Alternators on opposite sides of the motor, Connect them all via belts, put the Motor on max RPM and kickstart them. The motor will now convert 480 FE to 16000 SU, while the alternator converts 1000 SU to 360 FE

**Additional context**
- Mod version: 1.2.0
- Forge version: 47.2.1
- Create version: 0.5.1.f
![Bild_2023-12-05_140248724](https://github.com/mrh0/createaddition/assets/152984003/38784c0e-e2af-4a7d-8c3a-a8446da587f6)

**Comment by maxiangelo** [comment] 2023-12-05 13:43
Duplicate of #693

**Comment by mrh0** [comment] 2024-01-25 19:38
was solved in 1.2.1

**Closed as completed by mrh0** 2024-01-25 19:38 UTC
Labels: bug, forge
