### ISSUE TITLE
Fabric 1.18.2 New Crash

### ISSUE THREAD

**Issue by MacAndMayo** [mrh0/createaddition#306] opened 2022-08-03 19:02 UTC
**Describe the bug**
After updating three mods (The only one I can remember was Bookshelf), I could no longer launch Minecraft.

**To Reproduce**
(Unsure what steps I took)

**Additional context**
- Mod version: createaddition-1.18.2-20220621a
- Forge version: (Unclear how to check)
- Create version: create-1.18.2-0.5.0c-708

[crash-2022-08-03_14.52.37-client.txt](https://github.com/mrh0/createaddition/files/9254288/crash-2022-08-03_14.52.37-client.txt)

**Comment by FluffyBumblebees** [comment] 2022-08-04 04:44
This is a duplicate of https://github.com/mrh0/createaddition/issues/287

**Comment by mrh0** [comment] 2022-08-13 12:02
Fixed in 20220813a.

**Closed by mrh0** 2022-08-13 12:02 UTC
Labels: bug, fabric
