### ISSUE TITLE
Trains Powered & Made Faster By FE

### ISSUE THREAD

**Issue by ACactusWasTaken** [mrh0/createaddition#650] opened 2023-08-31 18:29 UTC
In base Create, trains can be powered by putting a burnable source in a chest which makes them fast. What if you could do the same with Accumulators and maybe being able to toggle this.

**Comment by QWXL** [comment] 2023-09-16 18:13
I hope this feature appears

**Comment by samuelh2005** [comment] 2024-01-08 16:19
Maybe a duplicate of #301?

**Comment by mrh0** [comment] 2024-01-25 19:42
Sorry, I'm not adding this

**Closed as completed by mrh0** 2024-01-25 19:42 UTC
Labels: suggestion
