### ISSUE TITLE
1.19.2 Crash when starting the Mod

### ISSUE THREAD

**Issue by Lupus26** [mrh0/createaddition#477] opened 2023-02-03 19:59 UTC
Describe the bug
Crashes on start up on latest version.

Additional context

Mod version: createaddition+1.19.2-1.19.2-20221218a.jar
Fabric version: 0.14.13
Create version: create-fabric-0.5.0.i-925+1.19.2.jar

**Comment by JoelZBub** [comment] 2023-02-04 17:10
This should be labelled "Incompatible with Create Fabric 0.5.0i", as this crash doesn't happen with previous Create Fabric version.

Crash report here:
https://hastebin.com/share/unotesabuq.yaml

**Comment by JoelZBub** [comment] 2023-02-04 17:11
Duplicate of #474

**Comment by serratedserenade** [comment] 2023-02-08 08:10
Current latest commit in fabric-1.19.2 branch seems to work with the latest Create Fabric version, have to wait till they push the release onto the site or compile yourself.

**Comment by stunlocked1** [comment] 2023-02-10 08:50
> Current latest commit in fabric-1.19.2 branch seems to work with the latest Create Fabric version, have to wait till they push the release onto the site or compile yourself.

createaddition-fabric+1.19.2-20230209a.jar, still crashes 

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createaddition'! 

Caused by: java.lang.NoClassDefFoundError: dan200/computercraft/api/peripheral/IPeripheralProvider (i dont have computer craft)

https://gist.github.com/stunlocked1/2228ef05e7503d9df90014fb71cb7ecd

**Comment by serratedserenade** [comment] 2023-02-10 12:19
> > Current latest commit in fabric-1.19.2 branch seems to work with the latest Create Fabric version, have to wait till they push the release onto the site or compile yourself.
> 
> createaddition-fabric+1.19.2-20230209a.jar, still crashes
> 
> java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createaddition'!
> 
> Caused by: java.lang.NoClassDefFoundError: dan200/computercraft/api/peripheral/IPeripheralProvider (i dont have computer craft)
> 
> https://gist.github.com/stunlocked1/2228ef05e7503d9df90014fb71cb7ecd

Oh I'm on `createaddition-fabric+1.19.2-20221128a`

**Comment by TobiPeterG** [comment] 2023-02-10 15:43
createaddition-fabric-1.19.2-20230209a still crashes for me.
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createaddition'!
https://gist.github.com/TobiPeterG/cabf867af1b4d3664711f9d00708575a

**Comment by JoelZBub** [comment] 2023-02-11 03:33
> createaddition-fabric-1.19.2-20230209a still crashes for me. java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createaddition'! https://gist.github.com/TobiPeterG/cabf867af1b4d3664711f9d00708575a
Look at this report again. Your crash is related to Computer Craft @TobiPeterG

**Comment by FluffyBumblebees** [comment] 2023-02-11 04:11
My bad, the dev hasnt uploaded my latest PR yet. The latest PR should fix this

**Comment by serratedserenade** [comment] 2023-02-11 04:53
@FluffyBumblebees Not sure what it is now, but it crashes if ComputerCraft is not enabled

**Comment by FluffyBumblebees** [comment] 2023-02-11 05:36
it doesnt, did you **compile** the latest PR

**Comment by serratedserenade** [comment] 2023-02-11 05:38
> it doesnt, did you **compile** the latest PR

 Oh I see the PR merged into that branch, I just didn't compile from that latest commit.

**Comment by FluffyBumblebees** [comment] 2023-02-11 05:51
Yeah its merged now, so the latest commit should fix ur issues

**Comment by serratedserenade** [comment] 2023-02-11 08:47
Compiled and ran without CC, works fine now

**Comment by mrh0** [comment] 2023-02-11 16:34
Fixed in 20230211a.

**Closed by mrh0** 2023-02-11 16:34 UTC
Labels: bug, fabric
