### ISSUE TITLE
[1.18.1] Failed to parse recipe

### ISSUE THREAD

**Issue by ModernGamingWorld** [mrh0/createaddition#201] opened 2022-01-21 21:50 UTC
**Describe the bug**

[15:45:57] [WARN ] Failed to parse recipe 'createaddition:mechanical_crafting/overcharged_hammer[create:mechanical_crafting]'! Falling back to vanilla: com.google.gson.JsonSyntaxException: Unknown item 'createaddition:overcharged_alloy'
[15:45:57] [WARN ] Failed to parse recipe createaddition:mechanical_crafting/overcharged_hammer[create:mechanical_crafting]: com.google.gson.JsonSyntaxException: Unknown item 'createaddition:overcharged_alloy'

**To Reproduce**

**Additional context**
- Mod version: 1.18.1-20220111b
- Forge version: 39.0.55
- Create version: 1.18.1_v0.4c

**Comment by mrh0** [comment] 2022-01-23 09:54
Dupe of #199

**Closed by mrh0** 2022-01-23 09:54 UTC
Labels: bug, in next update, minor issue
