### ISSUE TITLE
Fabric 1.19.2 Crash on start-up

### ISSUE THREAD

**Issue by Poke097** [mrh0/createaddition#475] opened 2023-02-03 04:24 UTC
**Describe the bug**
Crashes on start up on latest version.

**To Reproduce**
1. Launch the game.

**Additional context**
- Mod version: createaddition+1.19.2-1.19.2-20221218a.jar
- Fabric version: 0.14.13
- Create version:  create-fabric-0.5.0.i-925+1.19.2.jar
[crash-2023-02-02_22.23.48-client.txt](https://github.com/mrh0/createaddition/files/10575510/crash-2023-02-02_22.23.48-client.txt)

**Comment by JoelZBub** [comment] 2023-02-04 17:11
Duplicate of #474

**Comment by FluffyBumblebees** [comment] 2023-02-10 14:49
I think the latest release has resolved this issue. Care to test it on your system to see if it works on your system as well?

**Comment by mrh0** [comment] 2023-02-11 16:34
Fixed in 20230211a.

**Closed by mrh0** 2023-02-11 16:34 UTC
Labels: bug, fabric
